# Generated by Django 4.2.7 on 2023-11-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenseapp', '0004_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.BigIntegerField(),
        ),
    ]
